version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: procode-mysql
      working_dir: /application
      volumes:
        - ./application:/application
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=4rymt6ntq3vnouazs3d
        - MYSQL_DATABASE=procode
        - MYSQL_USER=someuser
        - MYSQL_PASSWORD=e6t54s6zh4s6bh54
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: procode-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: docker/php-fpm
      container_name: procode-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    composer:
      image: composer
      container_name: procode-composer
      volumes:
        - './application:/app'
      command: install